version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: fusion_flow_postgres
    environment:
      POSTGRES_DB: fusion_flow
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    container_name: fusion_flow_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    container_name: fusion_flow_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  postgres_data:
  mongo_data: